[package]
name = "Lab1"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
ndarray = "0.15.6"
linfa = "0.6.0"
linfa-trees = "0.6.0"
linfa-datasets = { version = "0.6.0", features = ["iris"] }